### PR TITLE
Guard -XDeriveDataTypeable extension with CPP

### PR DESCRIPTION
**Pull request by 3noch**
Consistency...

### CODE REVIEW

**Comment by phadej** [comment]
Just unnecessary CPP. Enabling unused pragma doesn't (yet) cause any warnings.

**Comment by 3noch** [comment]
Why guard the uses of `deriving Typeable` then if you don't support pre-`DeriveDataTypeable` GHCs?

**Comment by phadej** [comment]
`DeriveDataTypeable` is available for all ranges `some` supports. Yet it's derivable for types like `GOrdering` only since GHC-7.8 (When `Typeable` become polykinded).

**Comment by 3noch** [comment]
Ah ok makes sense. Thanks.

**Pull request closed without merging**
